# Generated by Django 4.0.4 on 2022-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('total_time', models.CharField(max_length=50)),
            ],
        ),
    ]
