# Generated by Django 4.0.4 on 2022-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fooditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=50)),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
